### ISSUE TITLE
Support a singleton instance in @MyComponent Scope ?

### ISSUE THREAD

**Issue by qdsfdhvh** [mori-atsushi/koject#194]
Hi, I have a problem when using `@MyComponent`:

```kotlin
@MyComponent
@Provides
class SingtionClass

@MyComponent
@Provides
class UseCase1(a: SingtionClass)

@MyComponent
@Provides
class UseCase2(b: SingtionClass)

// a != b
```

Some classes can migrate to `@Singleton`, but some can only be `@MyComponent`, so I want to be able to support `@MyComponent` scoped single instances. ❤️ 

I simply looked at it, `reslove()` will always new `ComponentExtras Container` every time, maybe it would be better to put container into `Map`?

```kotlin
public override fun resolve(id: Identifier, componentExtras: ComponentExtras<*>?): Any? {
    if (componentExtras == null) {
        return rootComponent.resolve(id)
    }
    return when (componentExtras::class) {
        _xx_xx_di_CustomComponentExtras_Holder.kClass -> 
            // here will always new
            _xx_xx_di_CustomComponent_Container(
                componentExtras,
                rootComponent,
            ).resolve(id)
        else -> rootComponent.resolve(id)
    }
}

⬇️

private val map = mutableMapOf<Any, Any>()

public override fun resolve(id: Identifier, componentExtras: ComponentExtras<*>?): Any? {
    if (componentExtras == null) {
        return rootComponent.resolve(id)
    }
    return when (componentExtras::class) {
       _xx_xx_di_CustomComponentExtras_Holder.kClass ->
            (map.getOrPut(componentExtras) {
                _xx_xx_di_CustomComponent_Container(
                    componentExtras,
                    rootComponent,
                )
            } as _xx_xx_di_CustomComponent_Container).resolve(id)
        else -> rootComponent.resolve(id)
    }
}
```

**Comment by mori-atsushi** [comment]
Thank you for your feedback.

Why can't you use Singleton?
Components are for injecting into special places such as Activities and Fragments, and you don't need to use them normally.

By the way, saving a Component Container with a map causes a memory leak.

**Comment by qdsfdhvh** [comment]
Such as the following: 

```kotlin
// in MyComponent Scope
@Singleton
@Provides
class ActivityHelper(
    val activity: Activity,
)

@Provide
class UseCase1(val helper: ActivityHelper)
```

I want to achieve the same effect as the `ActivityComponent` in `Hilt`, `Scope` is very useful, I hope `Koject` can support it 🥺 .

**Comment by mori-atsushi** [comment]
I understand you are asking for component scope.
I know that many DI container libraries such as Hilt and Koin provide custom scopes.
My rule of thumb is that using these features makes things harder to understand.
Therefore, Koject does not currently provide such a function.

I think that it is better to manage the lifetime of the instance in the code and pass it explicitly as an argument.
If you can provide a more specific useful use case, I'd be happy to consider it.

**Comment by qdsfdhvh** [comment]
> I think that it is better to manage the lifetime of the instance in the code and pass it explicitly as an argument.

I agree with you, but I still want to ask how to manage the lifecycle of instance, what about this (or other suggestions):

```kotlin

@Singleton
@Provides
class ActivityHelper {
    private activity : Activity? = null
    fun setup(activity: Activity) {
        // bind
    }
    fun doSomething() {
        requireNotNull(activity)
        // do
    }
}

@Provide
class UseCase1(val helper: ActivityHelper)
```

**Comment by mori-atsushi** [comment]
I would not recommend keeping an activity as a member of a singleton due to the increased risk of causing a memory leak.
Additionally, I am unable to answer your question as I do not understand the necessity of sharing the ActivityHelper.
Currently, it seems that creating a new ActivityHelper each time should not pose any problems.
If you can provide more specific code, I can consider it further.

**Comment by qdsfdhvh** [comment]
Thanks, I think I have some problems in using it myself, I will reorganize it and put together a demo for subsequent questions.
