### ISSUE TITLE
viewmodel for compose multiplatform

### ISSUE THREAD

**Issue by mahramane** [mori-atsushi/koject#290]
Hi
Is it possible to make a viewmodel that can be used for compose multiplatform and also be available using `injectViewModel()` inside composable functions?

**Comment by ColtonIdle** [comment]
yeah. interested in this as well. Maybe a better route would be... @mori-atsushi do you know if this can support precomposes viewmodel (since that is kmp compatible?)

**Comment by mori-atsushi** [comment]
`injectViewModel` is for Android ViewModel, it cannot be used with KMP.

> precomposes viewmodel

I'm not familiar with [precompose ViewModel](https://github.com/Tlaster/PreCompose/blob/master/docs/component/view_model.md), but the following might work.

```kotlin
@Provides
class SomeViewModel(
    val repository: SomeRepository
) : ViewModel() {
    /* ... */
}
```

```kotlin
val viewModel = viewModel { inject<SomeViewModel>() }
```
